### ISSUE TITLE
Start to sign image releases with cosign

### ISSUE THREAD

**Issue by mattmoor** [open-telemetry/opentelemetry-collector-releases#203]
### Is your feature request related to a problem? Please describe.

I'd like to be able to verify that the images we are consuming from `otel/opentelemetry-collector-contrib` on DockerHub were produced by this repo's release automation.

### Describe the solution you'd like

I'd like to see the workflow used to publish your images use `sigstore/cosign` keyless signing to sign the published images, e.g. like the actions sample [here](https://github.com/actions/starter-workflows/blob/7bc6d15b952547f496b440a3ae79ec141de3df5a/ci/docker-publish.yml#L85-L96).

There are three main pieces to this:
1. You need `id-token: write` permissions to generate an identity token for the workflow:
```yaml
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
```

2. You need to install `cosign`
```yaml
      - name: Install cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.12.1'
```

3. Sign the resulting image:
```yaml
      - name: Sign the published Docker image
        env:
          COSIGN_EXPERIMENTAL: "true"
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: cosign sign THE_IMAGE_DIGEST
```

This can then be used with assorted policy controllers to verify that the images published to DockerHub were produced by `.github/workflows/build-and-test.yml` even if the static DockerHub credentials have been compromised.

### Describe alternatives you've considered

You could also use `sigstore/cosign` to sign the images using a static key pair.  However, this requires managing another secret (the signing key), and publishing your own verification key.  Some projects (e.g. Google distroless) are signing things both ways, at least for now.
