### ISSUE TITLE
Distribution Proposal: Kubernetes-specific distribution

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-releases#357]
### Description

Many many users run the collector in Kubernetes today and the OpenTelemetry project has encouraged that behavior via the helm charts, operator, and Kubernetes-specific components.  To continue fostering the concept that the Collector is a terrific solution for monitoring Kubernetes I believe we need a more direct approach.

In order to facilitate a good default image for the OpenTelemetry-helm-charts, OpenTelemetry-operator, and any user looking to monitor Kubernetes, I propose that we introduce a new community-supported distribution specifically made for monitoring Kubernetes.  This distribution will provide an alternative to the Contrib distribution, which we do not recommend be used in production, for users who want to use a community supported image vs building their own.

### Benefits:
- **Ease of use for users**, especially those getting started.  Not all OTel users also want to manage a build pipeline for the Collector.  In order to build an image for Kubernetes today you must run ocb with your manifest AND include the output in a docker image that you then host somewhere. This image provides a solution for those looking to run the collector to monitor Kubernetes but also don’t want the burden of maintaining a collector build pipeline.
- **Following our own best practices**. Today the Collector and Operator helm charts use the Contrib image by default which enables bad practices if the user chooses to use the chart in production without modification.  The operator uses the Core repo, which is limiting for most users.  A Kubernetes-specific distribution would be in line with our best practices and would not limit users by default
- **Smaller than Contrib**. A Kubernetes-specific distribution should naturally be smaller than Contrib.  This follows our and industry best practices.

### Rules for components in the image:
This is only my initial ruleset, I am very interested in the community's opinions and feedback.

- Only includes components from Contrib and Core
- Only components that are Alpha or higher
- All receivers must facilitate the collection of data that is generated by Kubernetes or services running in Kubernetes
  - Although you could run a collector in Kubernetes to reach out to any endpoint, this image is not targeting that use case.  This image is for monitoring Kubernetes and the processes it runs.
- All components must be vendor-neutral. (I don’t see another way to ensure vendor neutrality in a community distribution that does not want to be the Contrib distribution - without this rule we'd have to allow every receiver and exporter in Contrib, at which point this image has no relevance)

### Proposed manifest:

Please carefully review this manifest.  I believe I have created it correctly based on the initial rules laid out above, but I may have missed a component or two that meets the criteria.

```
extensions:
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.79.0
  - gomod: go.opentelemetry.io/collector/extension/ballastextension v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/basicauthextension v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/bearertokenauthextension v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/headerssetterextension v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/httpforwarder v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/oauth2clientauthextension v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/hostobserver v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/k8sobserver v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/oidcauthextension v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage v0.79.0
    import: github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.79.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.79.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter v0.79.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.79.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/cumulativetodeltaprocessor v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatorateprocessor v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbyattrsprocessor v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricstransformprocessor v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/probabilisticsamplerprocessor v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/redactionprocessor v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/routingprocessor v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/servicegraphprocessor v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.79.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/fluentforwardreceiver v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/httpcheckreceiver v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8sclusterreceiver v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8seventsreceiver v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8sobjectsreceiver v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/receivercreator v0.79.0

connectors:
  - gomod: go.opentelemetry.io/collector/connector/forwardconnector v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/countconnector v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/servicegraphconnector v0.79.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/spanmetricsconnector v0.79.0
```

**Manifest Change Histroy**
- Removed dockerobserverextension and dockerstatsreceiver. Added loadbalancingexporter.
- Added receivercreator

### Additional Info

This topic has come up recently in the Collector SIG, but again in the Operator SIG.  Please see the SIG notes for details.

/cc @open-telemetry/operator-approvers
