### ISSUE TITLE
Create a PaaS distribution

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-releases#459]
This is a proposal for a use case related to the collector, alongside a select configuration and selection of components.

Heroku and other similar Platform-as-a-Service solutions allow to run the collector as a sidecar.

They have significant limitations in the size of the binary allowed to run, and limited use cases around data collection.

We currently maintain a Heroku buildpack project that could use this distribution moving forward:
https://github.com/signalfx/splunk-otel-collector-heroku

As you can see in the [config file used](https://github.com/signalfx/splunk-otel-collector-heroku/blob/main/setup/config_without_sa.yaml), the distribution uses a few select components.

Here is a sample manifest for it:
```
dist:
  module: github.com/open-telemetry/opentelemetry-collector-releases/paas
  name: otelcol-paas
  description: OpenTelemetry Collector PaaS
  version: 0.92.0
  output_path: ./_build
  otelcol_version: 0.92.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.92.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.92.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver v0.92.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.92.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.92.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.92.0

extensions:
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.92.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.92.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.92.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.92.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.92.0
```

**Comment by atoulme** [comment]
Yes, I swapped it for the transformprocessor, which I think might be more versatile in the future. We can add attributes, resource, span processors if we want, though transformprocessor will do the job.

**Comment by SaschaBrechmannVHV** [comment]
If i use the transformprocessor a config would look like this?
```
transform:
  error_mode: ignore
  trace_statements:
    - context: span
      statements:
        - set(attributes["otel_receiver"], "${ env:HOSTNAME }")
```
