### ISSUE TITLE
Add links to core and contrib to Github releases on releases from this repository

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-releases#498]
By default, the Github release only includes the changelog from this repository, but most users would care more about the changelog on core and contrib. 

I manually edited the release for v0.96.0 to include the core and contrib changelogs (see https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/v0.96.0) but we could make this automatic via goreleaser using https://goreleaser.com/customization/release/#custom-release-notes.

**Comment by Enzujp** [comment]
Hello @mx-psi , @jpkrohling if this is still unattended, I'd love to work on it!

**Comment by Enzujp** [comment]
@mx-psi Thank you, I'd get on it !

**Comment by Enzujp** [comment]
hello @mx-psi , while working on this, I discovered we can only automate using GoReleaser Pro, the feature that allows us link the change logs for core and contrib require the GoReleaser Pro and I don't have access to that. Is there perhaps another way to go about this ?

**Comment by TylerHelmuth** [comment]
@Enzujp correct, we use goreleaser pro. Seems we've run into https://github.com/open-telemetry/opentelemetry-collector-releases/issues/497.

**Comment by Enzujp** [comment]
Aw shucks, I was looking forward to working on this @TylerHelmuth

**Comment by Enzujp** [comment]
@mx-psi , Thank you very much I'd get on it.

**Comment by TylerHelmuth** [comment]
> it required a .goreleaser file in the root of the project

I am curious to see this solution.  How does it interact with the distro-specific .goreleaser files?

**Comment by Enzujp** [comment]
Hello @mx-psi , welcome back! This already happened, would you like for me to tag you to it ?

**Comment by mx-psi** [comment]
Oh, looks like that should be #504, I had a look but missed it :sweat_smile:  no need to tag me now!

**Comment by TylerHelmuth** [comment]
Adding the `.goreleaser.yaml` to the root of the directory did not work during the `v0.97.0` release: https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/v0.97.0

**Comment by Enzujp** [comment]
I'll go through the goreleaser docs and find a better way to do it. I'd find a fix.

**Comment by TylerHelmuth** [comment]
It might be easiest to use gh cli somehow. Also maybe try using [release note templates](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes).

**Comment by Enzujp** [comment]
@TylerHelmuth , I figured out what was missing! The repository specification is what's missing.

![goreleaser_screenshot](https://github.com/open-telemetry/opentelemetry-collector-releases/assets/100221308/3fa211f5-8349-41e9-9a40-07abb5a1a563)

**Comment by Enzujp** [comment]
Here's a sample of its usage and there's a release to show too : https://github.com/KenanBek/dbui/blob/main/.goreleaser.yml

**Comment by TylerHelmuth** [comment]
I am still concerned that the jobs specify a `workdir` that is different than root.  I noticed after the `v0.97.0` release that I had missed that your example repo does not do that: https://github.com/Enzujp/sample-releases/blob/ddcbd7645567cf99ed6b818f3c040c709ca775dc/.github/workflows/goreleaser.yaml#L36-L43

**Comment by Enzujp** [comment]
I'll make adjustments to that, and test the code to be sure it works as it should this time.

**Comment by Enzujp** [comment]
Hello @mx-psi , @TylerHelmuth after about a week of battling and reading most of the goreleaser docs, here's what I've found. Having the .`goreleaser` file in the root directory doesn't work for the` header release`. They make mention of `goreleaser release --release-notes ` command but it didn't work for templated text and there was no mention of how to use it for templated text so I experimented and searched and found this command `goreleaser release --release-header-tmpl=file`. It allows use of a markdown file, and here's a test of it, please check it out and let me know : https://github.com/Enzujp/sample-releases/actions/runs/8659835103/job/23746516462

**Comment by Enzujp** [comment]
Without the root as the working directory, this is the only other way to do it.

**Comment by TylerHelmuth** [comment]
@Enzujp this looks promising.  What happens if instead of a separate step you pass `--release-header-tmpl=release.md` as an argument like this:

```yaml
- name: Run GoReleaser
  uses: goreleaser/goreleaser-action@v5
  with: 
    distribution: goreleaser
    version: latest
    workdir: distributions/${{ inputs.distribution }}
    args: release --clean --release-header-tmpl=file
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by Enzujp** [comment]
Oh that's brilliant @TylerHelmuth ! It worked! 
Here's the link : https://github.com/Enzujp/sample-releases/actions/runs/8701172920/job/23862650984

**Comment by TylerHelmuth** [comment]
@Enzujp perfect! can you do one more test where 2 release jobs run with that argument (mimicking how Core, Contrib, and k8s all release at the same time in this repo)? I want to make sure they don't clash

**Comment by Enzujp** [comment]
I'm a little confused as to how I'm to go about this, please explain a little further.

**Comment by TylerHelmuth** [comment]
Can you update your release workflow with a second release job like 

```
  goreleaser-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4


      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with: 
          distribution: goreleaser
          version: latest
          workdir: distributions/otelcol-contrib
          args: release --clean --release-header-tmpl=../release.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by Enzujp** [comment]
Done @TylerHelmuth. Here's the link to the test : https://github.com/Enzujp/sample-releases/actions/runs/8711833942/job/23896805424

**Comment by TylerHelmuth** [comment]
Awesome, let's implement this option

**Comment by Enzujp** [comment]
@TylerHelmuth Got it. I only need include this in the release section right? Like this

- uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8 # v5.0.0
       ```
 with:
          distribution: goreleaser-pro
          version: latest
          workdir: distributions/${{ inputs.distribution }}
          args: continue --merge --timeout 2h --release-header-tmpl=../release.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_YES: true
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
```
