### ISSUE TITLE
`postinstall.sh` should detect chrooted environments to prevent dpkg failures

### ISSUE THREAD

**Issue by bowling233** [open-telemetry/opentelemetry-collector-releases#767]
### **Description**  
When installing `otelcol` in chrooted environments (e.g., `chroot` or `systemd-nspawn`), the installation fails because the `postinstall.sh` script attempts to run `systemctl` commands to start and enable systemd services.  

In these environments, `systemd` is not running as PID 1, which causes the script to fail. As a result:  
- `dpkg` enters a broken state.  
- Any subsequent package installations or updates fail because `dpkg` keeps retrying the failing `postinstall` script.

**This is extremely critical for automated workflows.**

### **Error Output**  
Below is the error message observed during installation:

```text
Setting up otelcol-contrib (0.115.1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/otelcol-contrib.service → /lib/systemd/system/otelcol-contrib.service.
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
dpkg: error processing package otelcol-contrib (--install):
 installed otelcol-contrib package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 otelcol-contrib
```

### **Steps to Reproduce**  
1. Enter a `chroot` or `systemd-nspawn` environment.  
2. Install `otelcol` using `dpkg` (e.g., `dpkg -i otelcol-contrib.deb`).  
3. Observe that the installation fails with the above error message due to `systemctl` commands in `postinstall.sh`.  

### **Expected Behavior**  
The script should check whether `systemd` is running before executing `systemctl` commands. If `systemd` is not active, the script should safely skip service-related operations.

### **Proposed Solution**  
Modify `postinstall.sh` to verify if `systemd` is running as PID 1 before calling `systemctl`. For example:

```bash
if ps --no-headers -o comm 1 | grep -q 'systemd'; then
    # Safe to run systemctl commands
    systemctl start otelcol-contrib
fi
```

This ensures that the `systemctl` commands only run in appropriate environments, avoiding failures in chrooted setups.

**Comment by mowies** [comment]
Maybe @netsandbox has some input here, since from past PRs he showed experience with these things 🤔 
@bowling233 are you willing to file a PR for this?

**Comment by netsandbox** [comment]
Systemd RPM macros append ` || :` to all systemctl commands to not fail package scripts: https://github.com/systemd/systemd/blob/main/src/rpm/macros.systemd.in

I can create a PR to add this here also.

**Comment by netsandbox** [comment]
By the way, how can I create the deb and rpm packages with goreleaser?

You use here goreleaser pro, so I can't create the packages locally with goreleaser (free).

**Comment by mowies** [comment]
> By the way, how can I create the deb and rpm packages with goreleaser?
> 
> You use here goreleaser pro, so I can't create the packages locally with goreleaser (free).

That feature of goreleaser is not actually part of the pro license so you should be able to use it with the free version as well.
But goreleaser internally uses [nFPM](https://github.com/goreleaser/nfpm) which is a free tool that you could also use standalone to generate your own linux services.

**Comment by bowling233** [comment]
There are too many configurations that depend on Pro features of GoReleaser. I tried modifying the relevant configuration, but it turned out to be too complex.  

```text
$ goreleaser
  ⨯ release failed after 0s                 
    error=
    │ yaml: unmarshal errors:
    │   line 8: field msi not found in type config.Project
    │   line 33: field prebuilt not found in type config.Build
    │   line 48: field prebuilt not found in type config.Build
    │   line 64: field prebuilt not found in type config.Build
    │   line 280: field monorepo not found in type config.Project
    │   line 282: field partial not found in type config.Project
```  

Instead, I managed to generate the package using a simple `nfpm` configuration file. For example, in `distributions/otelcol-contrib`:  

```yaml
name: "otelcol-contrib"
arch: "amd64"
platform: "linux"
version: "1.0.0"
section: "default"
priority: "extra"
maintainer: "The OpenTelemetry Collector maintainers <cncf-opentelemetry-maintainers@lists.cncf.io>"
description: "OpenTelemetry Collector - otelcol-contrib"
license: "Apache 2.0"
contents:
  - src: otelcol-contrib
    dst: /usr/bin/otelcol-contrib
  - src: otelcol-contrib.service
    dst: /lib/systemd/system/otelcol-contrib.service
  - src: otelcol-contrib.conf
    dst: /etc/otelcol-contrib/otelcol-contrib.conf
    type: config|noreplace
  - src: config.yaml
    dst: /etc/otelcol-contrib/config.yaml
    type: config|noreplace
scripts:
  preinstall: preinstall.sh
  postinstall: postinstall.sh
  preremove: preremove.sh
overrides:
  rpm:
    depends:
      - /bin/sh
```  

Then, I ran:  

```shell
$ nfpm pkg --packager deb --target /tmp/
using deb packager...
created package: /tmp/otelcol-contrib_1.0.0_amd64.deb
```  

I tested @netsandbox 's approach to append `|| :` to all systemctl commands in a Debian chrooted environment. While `systemctl` continues to fail, `dpkg` no longer enters a broken state. This has significantly improved CI pipeline stability.  

```shell
# dpkg -i otelcol-contrib_1.0.0_amd64.deb 
Selecting previously unselected package otelcol-contrib.
(Reading database ... 181740 files and directories currently installed.)
Preparing to unpack otelcol-contrib_1.0.0_amd64.deb ...
Unpacking otelcol-contrib (1.0.0) ...
Setting up otelcol-contrib (1.0.0) ...
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Created symlink /etc/systemd/system/multi-user.target.wants/otelcol-contrib.service → /lib/systemd/system/otelcol-contrib.service.
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```
