### ISSUE TITLE
Running Custom Otel Collector causing Exec format error

### ISSUE THREAD

**Issue by FoxeyesJK** [open-telemetry/opentelemetry-collector-releases#790]
Hi, I'm new to otel and trying to build a custom collector running our own docker image.

I've been reading the official documentation, and achieved following so far

1. using ocb compiler to generate go components with a custom manifest.yaml
2. built a docker image custom-collector:0.1.8 using Dockerfile
3. ran docker run, but faced a syntax error as below.

I'm stuck here running the docker container with what I have below. Any suggestion I can try?

- I am using M2 Chip MAC(ARM)
- I tried with the v0.116.0 and had a same problem. Seems like OCB doesn't have v0.116.1(latest) yet
- From scratch in Dockerfile LN4 was causing an error and switched to using alpine to at least running it

`docker run -it --entrypoint sh custom-collector:0.1.8`

```
/otelcol-contrib: line 1: ����

                              : not found

/otelcol-contrib: line 2: syntax error: unexpected "(" 
```

Dockerfile
```
FROM alpine:latest AS prep
RUN sed -i "s@http://dl-cdn.alpinelinux.org/alpine/@https://artifactory.aexp.com/alpine-raw/@g" /etc/apk/repositories
RUN sed -i "s@https://dl-cdn.alpinelinux.org/alpine/@https://artifactory.aexp.com/alpine-raw/@g" /etc/apk/repositories
RUN apk --update add ca-certificates

FROM alpine:latest

ARG USER_UID=10001
ARG USER_GID=10001
USER ${USER_UID}:${USER_GID}

COPY --from=prep /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --chmod=755 otelcol-custom/otelcol-custom /otelcol-contrib
COPY config.yaml /etc/otelcol-contrib/config.yaml
ENTRYPOINT ["/otelcol-contrib"]
CMD ["--config", "/etc/otelcol-contrib/config.yaml"]
EXPOSE 4317 4318 55678 55679
```

config.yaml
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: [0.0.0.0:4317](http://0.0.0.0:4317/)
      http:
        endpoint: [0.0.0.0:4318](http://0.0.0.0:4318/)

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  otlp/jaeger:
    endpoint: jaeger-all-in-one:4317
    tls:
      insecure: true

extensions:
  health_check:
  zpages:
    endpoint: :55679

service:
  extensions: [zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
```

manifest.yaml
```
dist:
  module: [github.com/betterstack-community/otelcol-custom](http://github.com/betterstack-community/otelcol-custom)
  name: otelcol-custom
  description: Custom OTel Collector distribution
  output_path: ./otelcol-custom
  version: 0.110.0

receivers:
  - gomod: [go.opentelemetry.io/collector/receiver/otlpreceiver](http://go.opentelemetry.io/collector/receiver/otlpreceiver) v0.110.0
  - gomod: [github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver](http://github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver) v0.110.0

processors:
  - gomod: [go.opentelemetry.io/collector/processor/batchprocessor](http://go.opentelemetry.io/collector/processor/batchprocessor) v0.110.0
  - gomod: [go.opentelemetry.io/collector/processor/memorylimiterprocessor](http://go.opentelemetry.io/collector/processor/memorylimiterprocessor) v0.110.0
  - gomod: [github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor](http://github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor) v0.110.0
  - gomod: [github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor](http://github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor) v0.110.0
  - gomod: [github.com/open-telemetry/opentelemetry-collector-contrib/processor/redactionprocessor](http://github.com/open-telemetry/opentelemetry-collector-contrib/processor/redactionprocessor) v0.110.0
  - gomod: [github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor](http://github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor) v0.110.0

exporters:
  - gomod: [go.opentelemetry.io/collector/exporter/debugexporter](http://go.opentelemetry.io/collector/exporter/debugexporter) v0.110.0
  - gomod: [go.opentelemetry.io/collector/exporter/otlpexporter](http://go.opentelemetry.io/collector/exporter/otlpexporter) v0.110.0

extensions:
  - gomod: [go.opentelemetry.io/collector/extension/zpagesextension](http://go.opentelemetry.io/collector/extension/zpagesextension) v0.110.0
  - gomod: [github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension](http://github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension) v0.110.0
  - gomod: [github.com/open-telemetry/opentelemetry-collector-contrib/extension/encoding/jaegerencodingextension](http://github.com/open-telemetry/opentelemetry-collector-contrib/extension/encoding/jaegerencodingextension) v0.110.0
  - gomod: [github.com/open-telemetry/opentelemetry-collector-contrib/extension/jaegerremotesampling](http://github.com/open-telemetry/opentelemetry-collector-contrib/extension/jaegerremotesampling) v0.110.0

providers:
  - gomod: [go.opentelemetry.io/collector/confmap/provider/envprovider](http://go.opentelemetry.io/collector/confmap/provider/envprovider) v1.16.0
  - gomod: [go.opentelemetry.io/collector/confmap/provider/fileprovider](http://go.opentelemetry.io/collector/confmap/provider/fileprovider) v1.16.0
  - gomod: [go.opentelemetry.io/collector/confmap/provider/httpprovider](http://go.opentelemetry.io/collector/confmap/provider/httpprovider) v0.110.0
  - gomod: [go.opentelemetry.io/collector/confmap/provider/httpsprovider](http://go.opentelemetry.io/collector/confmap/provider/httpsprovider) v0.110.0
  - gomod: [go.opentelemetry.io/collector/confmap/provider/yamlprovider](http://go.opentelemetry.io/collector/confmap/provider/yamlprovider) v0.110.0
```
