### ISSUE TITLE
Change the config.yaml of distributions to use the OTLP receiver instead of Prometheus

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-releases#836]
config.yaml contains a snippet to read internal metrics:
```
  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']
```

It should be using OTLP now.
