### ISSUE TITLE
failed to create SDK: binding address localhost:8888 for Prometheus exporter but not configured

### ISSUE THREAD

**Issue by cloudfy** [open-telemetry/opentelemetry-collector-releases#861]
Getting the following error, yet Prometheus is not configured at all.

otelcol-contrib.exe --config=file:config.yml

Error: failed to create SDK: binding address localhost:8888 for Prometheus exporter: listen tcp 127.0.0.1:8888: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
2025/03/06 14:15:52 collector server run finished with error: failed to create SDK: binding address localhost:8888 for Prometheus exporter: listen tcp 127.0.0.1:8888: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

Config file:

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch:
    timeout: 2s
    send_batch_size: 10
exporters:
  azuremonitor:
    connection_string: "..."
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
```

Environment:
* v0.121.0, Otel Contrib
* Windows 11, 64 bit
* command line, otelcol-contrib.exe --config=file:config.yml
